server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://47.94.92.138:3306/score?characterEncoding=UTF-8
    username: cq
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size:  50MB
      max-request-size: 10MB
mybatis:
  mapper-locations: mapper/*.xml       


logging:
  level:
    com:
     GradeManager:
      app:
       dao: TRACE